pool:
  vmImage: 'ubuntu-latest'

variables:
  NVD_API_KEY: 'b8d0a20b-f9a6-4d11-b6ab-f0df5e6b7160'

steps:
  # Install Node.js
  - task: UseNode@1
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  # Install project dependencies
  - script: |
      npm install
    displayName: 'Install Node.js Dependencies'

  # Install CycloneDX npm package
  - script: |
      npm install --save-dev @cyclonedx/cyclonedx-npm
    displayName: 'Install CycloneDX'

  # Generate SBOM using CycloneDX
  - script: |
      npx @cyclonedx/cyclonedx-npm --output-format JSON --output-file sbom.json
    displayName: 'Generate SBOM using CycloneDX'

  # Print the generated SBOM for verification (optional)
  - script: |
      cat sbom.json
    displayName: 'Print SBOM JSON'

  # Run OWASP Dependency-Check using Azure DevOps Extension
  - task: dependency-check@6
    inputs:
      projectName: 'Node.js-app'
      scanPath: '$(Build.SourcesDirectory)'
      format: 'JSON'
      uploadReports: true
      failOnCVSS: '7'
      outputFormat: 'ALL'
      nvdApiKey: '$(NVD_API_KEY)'
    displayName: 'Run OWASP Dependency-Check'

  # Publish OWASP Dependency-Check Report
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'dependency-check-report'
      artifactName: 'dependency-check-report'
      publishLocation: 'Container'
    displayName: 'Publish Dependency-Check Report'

  # Publish the SBOM to Azure Storage Account or another location
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'sbom.json'
      artifactName: 'sbom'
      publishLocation: 'Container'
    displayName: 'Publish SBOM'
